version: 0.0
os: linux
files:
  - source: helloworld
    destination: /app/
hooks:
  BeforeInstall:
  - source: stop.sh
    timeout: 300
    runas: root
  AfterInstall:
  - source: start.sh
    timeout: 300
    runas: root