version: 0.0
os: linux
files:
  - source: helloworld
    destination: /app/
hooks:
  BeforeInstall:
    - location: stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start.sh
      timeout: 300
      runas: root