version: 0.2

env:
  variables:
    SRC_DIR: src/github.com/shuntaka9576/codepipeline-demo
    BINARY_NAME: helloworld

phases:
  install:
    commands:
      - export GOPATH=/go && echo $GOPATH
      - type go && go version
      - go get -u github.com/golang/dep/cmd/dep
      - type dep && dep version && which dep
  pre_build:
    commands:
      # ソースファイルを移動
      - mkdir -p $GOPATH/${SRC_DIR}
      - mv ${CODEBUILD_SRC_DIR}/* $GOPATH/${SRC_DIR}
  build:
    commands:
      # Goバイナリを作成
      - cd $GOPATH/${SRC_DIR}
      - GOARCH=amd64 GOOS=linux go build -o ${BINARY_NAME}
artifacts:
    files:
       - $GOPATH/${SRC_DIR}/*
       - $GOPATH/${SRC_DIR}/script/*
    discard-paths: yes